INPUT = ""

all:
	cd test && python get_dressed_test.py

customized_test:
	cd test && python get_dressed_your_own_test.py $(INPUT)

default:
	cd test && python get_dressed_test.py

clean:
	cd lib && rm *.pyc